# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.2'
use_frameworks!

def shared_pods
  pod 'RealmSwift'
end 

target 'keyboardTest' do
  shared_pods
  pod 'KGFloatingDrawer', :path => "../"
  pod 'SwiftyJSON', '~> 2.2.1'
  pod 'Alamofire', '~> 1.3'
  pod 'PKHUD'
end

target 'keyboardTestTests' do
end

target 'HumanKontact WatchKit Extension' do
  shared_pods
end